name: UI

on:
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:
  push:
    branches: [develop]
    paths-ignore:
      - "**.md"
  schedule:
    # Run everday at midnight UTC / 5:30 IST
    - cron: "0 0 * * *"

concurrency:
  group: ui-develop-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        container: [framework, erpnext]
    steps:
      - uses: ./.github/workflows/setup.yml

      - name: Checkout
        uses: actions/checkout@v2

      - name: UI Tests
        run: cd ~/frappe-bench/ && bench --site test_site run-ui-tests erpnext_ui_tests/cypress/integration/${{ matrix.container }}/**/*.js --with-coverage --headless
        env:
          CYPRESS_RECORD_KEY: 60a8e3bf-08f5-45b1-9269-2b207d7d30cd

  #     - name: Upload Coverage Data
  #       uses: codecov/codecov-action@v2
  #       with:
  #         name: Cypress
  #         fail_ci_if_error: true
  #         root_dir: /home/runner/frappe-bench/apps/erpnext
  #         directory: /home/runner/frappe-bench/apps/erpnext_ui_tests/coverage/
  #         verbose: true
